/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DelegatedItem : TBase
  {
    private byte[] _wallet;
    private NodeApi.Amount _sum;
    private long _validUntil;

    public byte[] Wallet
    {
      get
      {
        return _wallet;
      }
      set
      {
        __isset.wallet = true;
        this._wallet = value;
      }
    }

    public NodeApi.Amount Sum
    {
      get
      {
        return _sum;
      }
      set
      {
        __isset.sum = true;
        this._sum = value;
      }
    }

    public long ValidUntil
    {
      get
      {
        return _validUntil;
      }
      set
      {
        __isset.validUntil = true;
        this._validUntil = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool wallet;
      public bool sum;
      public bool validUntil;
    }

    public DelegatedItem() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Wallet = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                Sum = new NodeApi.Amount();
                Sum.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I64) {
                ValidUntil = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("DelegatedItem");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Wallet != null && __isset.wallet) {
          field.Name = "wallet";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(Wallet);
          oprot.WriteFieldEnd();
        }
        if (Sum != null && __isset.sum) {
          field.Name = "sum";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          Sum.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.validUntil) {
          field.Name = "validUntil";
          field.Type = TType.I64;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ValidUntil);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("DelegatedItem(");
      bool __first = true;
      if (Wallet != null && __isset.wallet) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Wallet: ");
        __sb.Append(Wallet);
      }
      if (Sum != null && __isset.sum) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Sum: ");
        __sb.Append(Sum== null ? "<null>" : Sum.ToString());
      }
      if (__isset.validUntil) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ValidUntil: ");
        __sb.Append(ValidUntil);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
